//* admin login page / if admin.pwd === process.env.ADMIN_PWD
//!TODO: authenticate admin with jwt
//!TODO: add crud operations for authenticated user

import Head from 'next/head'
import Navbar from '../components/Navbar';
import Feed from '../containers/Feed';
import Footer from '../components/Footer';
import Doctors from '../containers/Doctors';

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="w-full overflow-hidden">
        <Navbar />
        <div className="w-full flex flex-row justify-evenly p-10 bg-gray-300">
          <Feed />
          <Doctors/>
        </div>
        <Footer />
      </main>
    </div>
  )
}

